### PR TITLE
fix: ponyfill SharedWorker

### LINKED ISSUE #107: Import of `Worker` breaks browsers w/out `SharedWorker` support
Import

```ts
import {Worker} from '@gravity-ui/app-builder/worker';
```

cause import of code that reference to `SharedWorker`, and this breaks browsers, that didn't have `SharedWorker` constructor

### PR DESCRIPTION
**Pull request by ValeraS**
Close #107

### CODE REVIEW

File: src/common/webpack/worker/web-worker.ts [hunk 1]
```diff
@@ -9,7 +12,7 @@ class WebWorker extends Worker {
     }
 }
 
-class SharedWebWorker extends SharedWorker {
+class SharedWebWorker extends SharedWorkerPolyfill {
```
Comment (ogonkov) [inline src/common/webpack/worker/web-worker.ts:15]: Can we move it to separate file, to have tree shacking?

File: src/common/webpack/worker/web-worker.mts [hunk 2]
```diff
@@ -1,6 +1,9 @@
 // eslint-disable-next-line camelcase
 declare let __webpack_public_path__: string;
 
+// @ts-expect-error ts does not find types in @okikio/sharedworker/@types/index.d.ts
```
Comment (ogonkov) [inline src/common/webpack/worker/web-worker.mts:4]: what type will be in project that will import SharedWorker form here? `unknown`?

File: src/common/webpack/worker/web-worker.ts (hunk 1 above)
Comment (ogonkov) [reply src/common/webpack/worker/web-worker.ts:15]: Not applicable

File: src/common/webpack/worker/web-worker.mts (hunk 2 above)
Comment (ogonkov) [reply src/common/webpack/worker/web-worker.mts:4]: I checked, somehow types comes from `src/index.ts` inside package

**Review by ogonkov — APPROVED** [review]
